// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    OuterComment: typeof import('./src/components/OuterComment.vue')['default']
    ThemeSwitchButton: typeof import('./src/components/ThemeSwitchButton.vue')['default']
    Tiptap: typeof import('./src/components/Tiptap.vue')['default']
  }
}

export {}
